/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.inf.ine5608.cliente;

import br.ufsc.inf.ine5608.rede.AtorNetGames;
import br.ufsc.inf.ine5608.rede.Jogador;
import br.ufsc.inf.ine5608.rede.Lance;
import br.ufsc.inf.ine5608.rede.Posicao;

/**
 *
 * @author Guilherme
 */
public class AtorJogador extends javax.swing.JFrame {

    private Tabuleiro tabuleiro;
    private AtorNetGames atorNetGames;
    private String nomeJogador;
    private Jogador jogador;

    /**
     * Creates new form InterfaceJogo
     */
    public AtorJogador() {
        initComponents();
        inicializar();
    }

    private void inicializar() {
        atorNetGames = new AtorNetGames(this);
        this.setSize(260, 330);
        this.setContentPane(getContentPane());
        this.setTitle("Warriors Of Chess");
        tabuleiro = new Tabuleiro();
    }

    public void iniciarPartida() {
        atorNetGames.iniciarPartidaRede();
    }

    public void receberLance(Lance lance) {
        tabuleiro.atualizarTabuleiro(lance);
    }

    //Método é chamado quando é recebida a solicitação de inicio
    public void iniciarPartidaRede(boolean vezDoJogadorLocal) {
        //Trata a inicialização do tabuleiro e da interfaçe grafica
        String nomeAdversario = atorNetGames.obterNomeAdversario();
        String nomeJogadorLocal = nomeJogador;
        if (vezDoJogadorLocal) {
            tabuleiro.inicializarJogadores(nomeJogadorLocal, nomeAdversario);
            jogador = tabuleiro.getJogadorLocal(true);
        } else {
            tabuleiro.inicializarJogadores(nomeAdversario,nomeJogadorLocal);
            jogador = tabuleiro.getJogadorLocal(false);            
        }
        
        tabuleiro.inicializarPersonagens();
    }

    public boolean enviarLance(Lance lance) {
        if (atorNetGames.isVezDoJogadorLocal()) {
            boolean lanceValido = tabuleiro.validarLance(lance);
            if (lanceValido) {
                atorNetGames.enviarLance(lance);
                return true;
            }
        }
        return false;
    }

    public void conexaoPerdida() {
        if (tabuleiro.IsPartidaEmAndamento()){
            
        } else{
            btn_conectar.setText("Conectar");
            btn_conectar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_enviar_lance = new javax.swing.JButton();
        label_vezDeQuem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_conectar = new javax.swing.JButton();
        txt_field_player_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_regras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 400));

        btn_enviar_lance.setText("Enviar");
        btn_enviar_lance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_lanceActionPerformed(evt);
            }
        });

        label_vezDeQuem.setText("VEZ DE QUEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(label_vezDeQuem)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_enviar_lance)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_vezDeQuem)
                .addGap(96, 96, 96)
                .addComponent(btn_enviar_lance)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        txt_field_player_name.setText("Player1");

        jLabel1.setText("Nome");

        btn_regras.setText("Regras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_regras)
                    .addComponent(btn_conectar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_field_player_name, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_field_player_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addComponent(btn_conectar)
                .addGap(45, 45, 45)
                .addComponent(btn_regras)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        String nomeJogador = txt_field_player_name.getText();
        if (!atorNetGames.isConectado() && atorNetGames.conectar("127.0.0.1", nomeJogador)){
            this.nomeJogador = nomeJogador;
            btn_conectar.setText("Procurando Adversário");
            btn_conectar.setEnabled(false);
        }
    }//GEN-LAST:event_btn_conectarActionPerformed

    private void btn_enviar_lanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_lanceActionPerformed
        Lance lance =new Lance();
        lance.setPosFinal(new Posicao(0, 3));
        lance.setPosInicial(new Posicao(0, 0));
        
        enviarLance(lance);
    }//GEN-LAST:event_btn_enviar_lanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtorJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtorJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtorJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtorJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtorJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private javax.swing.JButton btn_enviar_lance;
    private javax.swing.JButton btn_regras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_vezDeQuem;
    private javax.swing.JTextField txt_field_player_name;
    // End of variables declaration//GEN-END:variables

}
